settings:
  claimPrice: 750
  systemID: 'Hack_the_Gibson'
messages:
  claimSold: '&aYou have sold your claim for &e%price%&a.'
  claimNotForSale: '&cThis claim is not for sale.'
  claimNotOwned: '&cYou do not own this claim.'
  claimAlreadyForSale: '&cThis claim is already for sale.'
  invalidItem: '&cInvalid item.'
  noClaimsForSale: '&cNo claims for sale.'
  claimNoLongerExists: '&cThis claim no longer exists.'
  claimNoLongerAvailable: '&cThis claim is no longer available.'
  claimPurchased: '&aYou have purchased this claim for &e%price%&a.'
  claimTeleporting: '&aTeleporting to claim in 5 seconds.'
  claimTeleported: '&aYou have teleported to this claim.'
  claimUnlisted: '&aYou have unlisted this claim.'
  claimLogged: '&aClaim has been logged.'
  claimDoesNotExist: '&cThis claim does not exist.'
  teleportingToClaim: '&aTeleporting to claim in 5 seconds...'
  teleportedToClaim: '&aYou have been teleported to the claim.'
  cannotUnlistNotOwned: '&cYou cannot unlist a claim that you do not own.'
  noPermissionToLogClaims: '&cYou do not have permission to log claims.'
  invalidClaimItem: '&cThis item does not represent a valid claim.'
  cannotPurchaseOwnClaim: '&cYou cannot purchase your own claim.'
  notEnoughMoney: '&cYou do not have enough money to purchase this claim. You have
    &e%current_balance%&c, but the claim costs &e%claim_price%&c.'
booleans:
  enableClaimExpiration: true
  requireMoney: true